apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "frontend-dashboard-informatica"
  description: "Dashboard"
  tags:
    - frontend
  annotations:
    localhost/project-slug: apresentacao/frontend-dashboard-informatica
    gitlab.com/project-slug: apresentacao/frontend-dashboard-informatica
    'backstage.io/kubernetes-label-selector': 'app=frontend-dashboard-informatica'
    sonarqube.org/project-key: frontend-dashboard-informatica
    backstage.io/code-coverage: scm-only
  links:
    - url: https://localhost/app/frontend-dashboard-informatica
      title: Public URL
      icon: public

    - url: https://localhost/apresentacao/frontend-dashboard-informatica.git
      title: Git HTTPS URL
      icon: gitlab

    - url: https://frontend-dashboard-informatica.demo-aws.com.br
      title: Internal URL
spec:
  type: website
  owner: "user:default/root"
  lifecycle: experimental
  system: system:default/apresentacao-system
  consumesApis:
    - api:default/backend-dashboard-api
  dependsOn:
    - component:default/backend-dashboard
    - resource:default/fila-mensageria
